examples/btc_miniscript.rs
sandbox/src/App.tsx
src/btc.rs
src/wasm/mod.rs

The keypath is unused when registering policies, as it is already present in the script config keys list. It is only required for multisig script registrations at the moment.

btc: make keypath optional for script registrations

---

sandbox/src/App.tsx
src/communication.rs
src/lib.rs
src/usb.rs
src/wasm/connect.rs
src/wasm/mod.rs
webhid.js

Before, `BitBox::from()` internally created a U2fCommunication framing layer. We remove this and fold it into the ReadWrite trait that `BitBox::from` already takes. This way, the connection code can choose the framing. This will allow making a BitBoxBridge communication layer, which uses a modified u2f framing protocol.

refactor communication by making the framing protocol configurable

---

Cargo.toml

If one wants to activate `serde`, it should not activate `dep:serde-wasm-bindgen`. That part is really only needed for wasm.

Cargo: improve serde wasm feature activation

---

src/eth.rs
src/lib.rs
src/util.rs
src/wasm/mod.rs

BitBox02 enforces no leading zeroes in these fields. Better UX for library users if they don't have to strip it manually.

eth: remove leading zeroes in eth tx fields

---

README.md

This commit restructures the README to make it easier to understand and adds additional information for M1 Mac users.

readme: improve setup instructions

---

Cargo.toml
Makefile
ci.sh
examples/multithreaded.rs
examples/singlethreaded.rs
src/communication.rs
src/lib.rs
src/noise.rs
src/runtime.rs
src/usb.rs
src/util.rs
src/wasm/connect.rs
src/wasm/noise.rs

Generally, the hidapi based communication should be single-threaded, as on macOS, we have seen communication issues when the hidapi calls move between threads. See https://github.com/libusb/hidapi/issues/503.
The above issue is unresolved and unexplained, and might only happen in combination with the Go runtime, Nevertheless, it is safer to use it only single-threaded, to avoid potential issues.
This commit enables Sync+Send (multithreading) by activating the "multithreaded" feature for when multithreading is required. Sync/Send cannot be activated in WASM as the function pointers in JsReadWrite do not implement Sync/Send.

allow for multithreaded use of PairingBitBox and PairedBitBox

---

Cargo.toml
ci.sh
scripts/build-protos.rs
src/btc.rs
src/cardano.rs
src/eth.rs
src/keypath.rs
src/shiftcrypto.bitbox02.rs

For eth.rs serde/serde_json is not optional to parse EIP712 messages.
The rest is only needed for WASM to communicate the structs to or from JS.

Cargo: remove serde feature

---

Cargo.lock
Cargo.toml
src/lib.rs

Difficult otherwise to make external implementation of NoiseConfig trait.
Fixes #39

make NoiseConfigData public

---

Cargo.lock
Cargo.toml
src/lib.rs

So that the NoiseConfig trait (which relies on `Threading`) can be implemented by clients.
Fixes #42

make util::Threading public

---

src/lib.rs
src/noise.rs

I successfully have an external implementation of NoiseConfig.
I think no error was returned by the compiler for the trait, because the ConfigError is indeed public in the module, but the module is private in lib.rs
close #44

Make noise ConfigError public

---

Cargo.toml
Makefile
ci.sh
examples/btc_sign_msg.rs
src/btc.rs

Addresses the request in the issue : #49 
The implementation of BTC message signing has been completed and it also supports antiklepto verification. Furthermore, a test is added as an example in 'examples' folder.

src: BTC sign message implemented and tested

---

examples/btc_sign_msg.rs
sandbox/src/Bitcoin.tsx
src/btc.rs
src/wasm/mod.rs
src/wasm/types.rs

After implementing BTC message signing for Rust API, further extensions are added to make wasm expose this functionality to TypeScript API. Finally, an extra field added under the Bitcoin section of sandbox UI app for BTC message signing.

btc: Expose sign_message() to TS API and create UI

---

Cargo.lock
Cargo.toml
sandbox/package-lock.json

btc_sign_msg() added to Rust and WASM.

Cargo.toml: bump version

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
LICENSE
ci.sh
src/communication.rs
src/constants.rs
src/error.rs
src/lib.rs
src/simulator.rs
tests/.gitignore
tests/simulator_tests.rs
tests/simulators.json
tests/subtests/mod.rs
tests/subtests/test_btc_psbt.rs

More or less the same as 
https://github.com/BitBoxSwiss/bitbox02-api-go/pull/97

tests: test against bitbox02 simulators

---

.github/workflows/rust.yml

Nightly quite often breaks CI by introducing new clippy linters etc, which disrupts one's work when one wants to land a PR whose CI suddenly fails for unrelated reasons.
Sometimes, the new linters are also broken and result in false positives. The one that prompted this commit is a false positive about needless_return like this:
https://github.com/rust-lang/rust-clippy/issues/13526
```
error: unneeded `return` statement
--> tests/simulator_tests.rs:212:51
|
212 |       for simulator_filename in simulator_filenames {
|  ___________________________________________________^
213 | |         println!("Simulator tests using {}", simulator_filename);
214 | |         let _server = Server::launch(&simulator_filename);
...   |
244 | |         test_btc(&paired_bitbox).await
245 | |     }
```
(there …

ci: remove actions using Rust nightly

---

src/eth.rs

```
error: the following explicit lifetimes could be elided: 'a
--> src/eth.rs:366:10
|
366 |     impl<'a> Either<'a> {
|          ^^         ^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
= note: `-D clippy::needless-lifetimes` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::needless_lifetimes)]`
help: elide the lifetimes
|
366 -     impl<'a> Either<'a> {
366 +     impl Either<'_> {
```

eth: fix clippy error

---

CHANGELOG-npm.md
CHANGELOG-rust.md
sandbox/src/Bitcoin.tsx
src/wasm/types.rs

05b3cb5 already updated the protobuf files.

btc: add support for regtest

---

CHANGELOG-npm.md
CHANGELOG-rust.md
src/btc.rs
tests/simulators.json
tests/subtests/test_btc_psbt.rs

This mostly involves fixing PSBT signing to be able to handle Taproot leaf script spends.
Integration tests with the simulator are added. The signed PSBTs are checked to be correctly signed by rust-miniscript and rust-bitcoinconsensus.

btc: support Taproot policies

---

src/wasm/types.rs

Some types had one, some didn't.

wasm: add semicolon consistently

---

webhid.js

Motivation: if connecting through webhid, browser keeps showing prompt to select device even though the device has already been paired. This PR fixes that behavior and reuses existing pairing, avoiding the redundant prompt.
Ledger js library works similarly:
https://github.com/LedgerHQ/ledger-live/blob/a77b0c1236302f4fb58b61cf7d0df5632cdc86e1/libs/ledgerjs/packages/hw-transport-webhid/src/TransportWebHID.ts#L110
https://github.com/LedgerHQ/ledger-live/blob/a77b0c1236302f4fb58b61cf7d0df5632cdc86e1/libs/ledgerjs/packages/hw-transport/src/Transport.ts#L295

webhid: avoid unecessary device selection prompt if device already connected

---

CHANGELOG-rust.md
Cargo.toml
Makefile
examples/simulator.rs
src/simulator.rs

We only added the simulator feature for the unti tests, which run in a single thread. This adds support for using the simulator function with the multithreaded feature.

fix multithreaded+simulator combination

---

examples/btc_miniscript.rs
examples/btc_sign_msg.rs
examples/btc_sign_psbt.rs
examples/btc_signtx.rs
examples/cardano.rs
examples/eth.rs
examples/multithreaded.rs
examples/singlethreaded.rs
src/eth.rs
src/wasm/types.rs
tests/util/mod.rs

Clippy on the beta toolchain will complain if the variables are not used directly in the string.

fix: use variables directly in `format!` string
